spring:
    datasource:
        url: ${BOOKRENTAL_DB_HOST}:${BOOKRENTAL_DB_PORT}/${BOOKRENTAL_DB_NAME}
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: create